---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-local
  template:
    metadata:
      labels:
        app: config-server-local
    spec:
      containers:
      - name: config-server-local
        image: 405834051687.dkr.ecr.us-east-1.amazonaws.com/configserverlocal:5
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8888"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://dashboard-eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-local
spec:
  type: ClusterIP
  selector:
    app: config-server-local
  ports:
  - name: http
    port: 8888
    targetPort: 8888
