# Lab / dev: şifreleri production'da Sealed Secrets veya External Secrets ile değiştirin.
apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
type: Opaque
stringData:
  postgres-password: "123456789"
