apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configserverlocal.yaml
  - dashboardeurekaserver.yaml
  - accountservice.yaml
  - ledgerservice.yaml
  - fraudservice.yaml
  - notificationservice.yaml
  - apigatewayservice.yaml
  - redis.yaml
