server:
  port: 9593

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

spring:

  cloud:
    function:
      definition: uppercase

  datasource:
    url: jdbc:postgresql://localhost:9999/Micro_FraudServiceDB   # PostgreSQL veritabanı URL'si (Docker)
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    bindings:
      processMessage-in-0:
        destination: incoming-topic
      processMessage-out-0:
        destination: outgoing-topic
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html


resilience4j:
  circuitbreaker:
    instances:
      fraudService:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s